version: '3.8'

services:
  mongodb-backend-app-marcelo:
    image: mongo
    container_name: mongodb-backend-app-marcelo
    ports:
      - "27017:27017"
    volumes:
      - .:/home/node/app
    attach: false # desabilita ou habilita os logs do mongo
    networks:
      - api
    command: mongod --bind_ip_all

  minio-backend-app-marcelo:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # Porta da API S3
      - "9001:9001"   # Porta do console web
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    networks:
      - api
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  kafka-ui-backend-app-marcelo:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    attach: false 
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-backend-app-marcelo:9093
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-backend-app-marcelo:2181
    depends_on:
      - kafka-backend-app-marcelo
    networks:
      - api

  zookeeper-backend-app-marcelo:
    image: wurstmeister/zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_LISTENER_PORT: 2181
      ZOOKEEPER_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
    ports:
      - "2181:2181"
    networks:
      - api
      
  kafka-backend-app-marcelo:
    image: wurstmeister/kafka:latest
    container_name: kafka-backend-app-marcelo
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka-backend-app-marcelo:9093
      KAFKA_LISTENERS: INSIDE://kafka-backend-app-marcelo:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_INTERFACES: INSIDE
      KAFKA_LISTENER_NAMES: INSIDE
      KAFKA_LISTENER_INTERNAL: INSIDE://kafka-backend-app-marcelo:9093
      KAFKA_LISTENER_MODE: BROKER
      KAFKA_ADVERTISED_LISTENER: INSIDE://kafka-backend-app-marcelo:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-backend-app-marcelo:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE 
    ports:
      - "9093:9093"
    networks:
      - api
    depends_on:
      - zookeeper-backend-app-marcelo
  redis-master-backend-app-marcelo:
    image: redis
    container_name: redis-master-backend-app-marcelo
    command: ["redis-server", "--requirepass", "redis_pass"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    attach: false
    networks:
      redis-network:
        ipv4_address: 172.30.0.3

  redis-slave-backend-app-marcelo:
    image: redis:latest
    container_name: redis-slave-backend-app-marcelo
    command: ["redis-server", "/usr/local/etc/redis/redis-slave.conf"]
    attach: false
    depends_on:
      - redis-master-backend-app-marcelo
    volumes:
      - ./redis/redis-slave.conf:/usr/local/etc/redis/redis-slave.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      redis-network:
        ipv4_address: 172.30.0.4

  redis-sentinel-backend-app-marcelo:
    image: redis:7
    container_name: redis-sentinel-backend-app-marcelo
    volumes:
      - ./redis/sentinel.conf:/etc/redis/sentinel.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    networks:
      redis-network:
        ipv4_address: 172.30.0.5
    ports:
      - "26379:26379"
    depends_on:
      - redis-master-backend-app-marcelo

  redis-sentinel2-backend-app-marcelo:
    image: redis:7
    container_name: redis-sentinel2-backend-app-marcelo
    volumes:
      - ./redis/sentinel.conf:/etc/redis/sentinel.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    networks:
      redis-network:
        ipv4_address: 172.30.0.6
    ports:
      - "26380:26379"
    depends_on:
      - redis-master-backend-app-marcelo

  redis-sentinel3-backend-app-marcelo:
    image: redis:7
    container_name: redis-sentinel3-backend-app-marcelo
    volumes:
      - ./redis/sentinel.conf:/etc/redis/sentinel.conf
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command: ["redis-sentinel", "/etc/redis/sentinel.conf"]
    networks:
      redis-network:
        ipv4_address: 172.30.0.7
    ports:
      - "26381:26379"
    depends_on:
      - redis-master-backend-app-marcelo

  app:
    build: .
    depends_on:
      - mongodb-backend-app-marcelo
      - minio-backend-app-marcelo
      - kafka-backend-app-marcelo
      - zookeeper-backend-app-marcelo
      - redis-sentinel-backend-app-marcelo
      - redis-sentinel2-backend-app-marcelo
      - redis-sentinel3-backend-app-marcelo
    entrypoint: .docker/entrypoint.sh
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/node/app
    networks:
        - api
        - redis-network
    environment:
        URL: "http://localhost:${PORT}/"
        TZ: America/Sao_Paulo
        DBAAS_MONGODB_ENDPOINT: mongodb://mongodb-backend-app-marcelo:27017/backend-app-marcelo
        AWS_ENDPOINT: http://minio-backend-app-marcelo:9000/
        AWS_ACCESS_KEY_ID: minioadmin
        AWS_SECRET_ACCESS_KEY: minioadmin123
        REGIONAWS: us-east-1
        ENV_AMB: LOCAL
        APP_VERSION: Local version  
        KAFKA_BROKER: kafka-backend-app-marcelo:9093
        KAFKA_GROUP_ID: nestjs-consumer-group
        KAFKA_CLIENT_ID: nestjs-consumer-client
        DBAAS_SENTINEL_HOSTS: 'redis-sentinel-backend-app-marcelo,redis-sentinel2-backend-app-marcelo,redis-sentinel3-backend-app-marcelo'
        DBAAS_SENTINEL_PORT: 26379
        DBAAS_SENTINEL_SERVICE_NAME: mymaster
        DBAAS_SENTINEL_PASSWORD: redis_pass 
        EXPIRES_TOKEN: 48h

  mongodb-seed-backend-app-marcelo: # rodar esse container, importa os dados(json) no mongodb local
    image: mongo
    container_name: mongodb-seed-backend-app-marcelo
    depends_on:
      - mongodb-backend-app-marcelo
    volumes:
        - .:/home/node/app
    networks:
      - api
    attach: true
    command:
      - sh
      - -c
      - | 
        mongoimport --uri mongodb://mongodb-backend-app-marcelo:27017/backend-app-marcelo --collection Users --file home/node/app/src/mocks/users.mock.json --jsonArray &&
        mongoimport --uri mongodb://mongodb-backend-app-marcelo:27017/backend-app-marcelo --collection Chats --file home/node/app/src/mocks/chats.mock.json --jsonArray &&
        mongoimport --uri mongodb://mongodb-backend-app-marcelo:27017/backend-app-marcelo --collection ChatMessage_67f9f61c571627cad4f95818 --file home/node/app/src/mocks/chats_conversation.mock.json --jsonArray &&
        mongoimport --uri mongodb://mongodb-backend-app-marcelo:27017/backend-app-marcelo --collection Allowed_file_types --file home/node/app/src/mocks/upload-type.mock.json --jsonArray &&
        mongoimport --uri mongodb://mongodb-backend-app-marcelo:27017/backend-app-marcelo --collection Files --file home/node/app/src/mocks/upload-files.mock.json --jsonArray

  minio-seed-backend-app-marcelo:
    image: minio/mc
    container_name: minio-seed-backend-app-marcelo
    depends_on:
      - minio-backend-app-marcelo
    volumes:
    - ./.docker/minio-seed.sh:/seed/minio-seed.sh
    - ./src/mocks/imgs:/seed/images
    entrypoint: ["/bin/sh", "-c", "/seed/minio-seed.sh"]
    networks:
      - api

volumes: 
  minio_data:

networks:
  redis-network:
    ipam:
      config:
        - subnet: 172.30.0.0/16
  api:
    driver: bridge
