import type { Config } from "jest";
import { compilerOptions } from "./tsconfig.json";
import { pathsToModuleNameMapper } from "ts-jest";
const config: Config = {
  moduleFileExtensions: ["ts", "js", "mjs", "json"],
  rootDir: ".",
  preset: "ts-jest",
  testEnvironment: "node",
  testRegex: ".*\\.spec\\.ts$",
  transform: {
    "^.+\\.(t|j)s$": "ts-jest",
  },
  collectCoverageFrom: ["src/**/*.(t|j)s"],
  coverageDirectory: "./coverage",
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths, {
    prefix: "<rootDir>",
  }),
  transformIgnorePatterns: ["node_modules/(?!(file-type)/)"],
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "/dist/",
    ".*model\\.ts$",
    ".*schema\\.ts$",
    ".*config\\.ts$",
    ".*module\\.ts$",
    ".*main\\.ts$",
    ".*dto\\.ts$",
    "/dto/",
    "\\.dto\\.ts$",
    "/schemas/",
    "/models/",
    "\\.schema\\.ts$",
    ".*jwt-auth.guard\\.ts",
    ".*local-auth.guard\\.ts",
    "/.vercel/",
    ".*tmp\\.ts$",
    "/validator/",
    "/test/",
    "/mock/",
    "/mocks/",
    "/configs/",
    "/config/",
    "/interfaces/",
    ".eslintrc.js",
    "commitlint.config.js",
    "/coverage/",
    "sonar-project.ts",
    "/enums/",
    "sonar-project.ts ",
    "changelog.config.js",
    "sonar-project.ts",
  ],
};

export default config;
