export const CHAT_PRODUCER_SERVICE_CREATE_CHAT =
  "CHAT_PRODUCER_SERVICE_CREATE_CHAT";
export const CHAT_PRODUCER_SERVICE_CREATE_MESSAGE =
  "CHAT_PRODUCER_SERVICE_CREATE_MESSAGE";
export const CHAT_PRODUCER_SERVICE_UPDATE_MESSAGE =
  "CHAT_PRODUCER_SERVICE_UPDATE_MESSAGE";
export const CHAT_PRODUCER_SERVICE_DELETE_MESSAGE =
  "CHAT_PRODUCER_SERVICE_DELETE_MESSAGE";
export const CHAT_PRODUCER_SERVICE_DELETE_CHAT =
  "CHAT_PRODUCER_SERVICE_DELETE_CHAT";
