name: CI com SonarCloud e pnpm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '8'

      - name: Instalar dependências
        run: pnpm install

      - name: Rodar testes com cobertura
        run: pnpm test:cov
      
      - name: Verificar arquivo de cobertura
        run: ls -l coverage/lcov.info
      - name: Habilitar debug
        run: echo "SONAR_SCANNER_OPTS=-X" >> $GITHUB_ENV
        
      - name: Análise com SonarCloud
        run: pnpm sonar
        env:
          SONAR_TOKEN: 45df69f09ace91aa3d7660a10f0e725aeb08bcb0
          SONAR_URL: https://sonarcloud.io
