name: CI com SonarCloud e pnpm

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '8'

      - name: Instalar dependências
        run: pnpm install

      - name: Rodar testes com cobertura
        run: pnpm test:cov

      - name: Instalar SonarScanner
        run: |
          curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner

      - name: Análise com SonarCloud
        run: sonar-scanner
        env:
          SONAR_TOKEN: '6661c8028a00484cfa1be57bfff6c1785dc4e994'
